# Numpy

In [1]:
import numpy as np
import time


In [2]:
""" Vectors""" #Vectors is a specific type of array with 1-D it can be row vector or column vector
               # all vectors are arrays but not vice versa
#vector 
a = np.zeros(4)
print(f"a={a} ,shape = {a.shape} ,data type = {a.dtype}")
#vector
a = np.zeros((1,4)) 
print(f"a={a} ,shape = {a.shape} ,data type = {a.dtype}")
#vector (column vector)
a = np.zeros((4,1)) 
print(f"a={a} ,shape = {a.shape} ,data type = {a.dtype}")
#array
a=np.array([[1,2,3,4],[1,2,3,4]])
print(f"a={a} ,shape = {a.shape} ,data type = {a.dtype}")
#vector
a= np.array([1,2,3,4]) 
print(f"a={a} ,shape = {a.shape} ,data type = {a.dtype}")

#vector (column vector)
a = np.array([1, 2, 3, 4]).reshape(-1, 1)
print(f"a={a} ,shape = {a.shape} data type = {a.dtype}")



a=[0. 0. 0. 0.] ,shape = (4,) ,data type = float64
a=[[0. 0. 0. 0.]] ,shape = (1, 4) ,data type = float64
a=[[0.]
 [0.]
 [0.]
 [0.]] ,shape = (4, 1) ,data type = float64
a=[[1 2 3 4]
 [1 2 3 4]] ,shape = (2, 4) ,data type = int32
a=[1 2 3 4] ,shape = (4,) ,data type = int32
a=[[1]
 [2]
 [3]
 [4]] ,shape = (4, 1) data type = int32


# Indexing

In [3]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a) 

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)
    

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


# Slicing<br>
start: The starting index (inclusive).
stop: The stopping index (exclusive).
step: The step size (default is 1).

In [4]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


Some operations on vector (1-D array)

In [5]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


<img src = ./Images/b11.png></img>

In [6]:
"""Dot product using for loop"""
def my_dot(a,b):
    x=0
    for i in range(a.shape[0]):
        x=x+ (a[i]*b[i])
        
    return x

print(f"Dot product of a = [1,2,3] and b= [7,8,9] = {my_dot(np.array([1,2,3]),np.array([7,8,9]))}  ")


Dot product of a = [1,2,3] and b= [7,8,9] = 50  


In [7]:
"""Dot product using np.dot"""
a=np.array([1,2,3])
b=np.array([7,8,9])
c=np.dot(a,b)
print(f"Dot product of a = [1,2,3] and b= [7,8,9] = {c}  ")


Dot product of a = [1,2,3] and b= [7,8,9] = 50  


Defference in time between vectorization and for loop

In [8]:
a = np.random.rand(10000000) #very large random array
b = np.random.rand(10000000) #very large random array
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(f"np.dot(a,b)= {c:.4f}")
print(f"time = {(toc-tic)} second")

tic = time.time()
c= my_dot(a,b)
toc = time.time()

print(f"Dot product ={c:.4f}" )
print(f"time = {toc-tic} seconds")

print(np.random.random_sample(5))
print(np.random.rand(5))


np.dot(a,b)= 2499266.1064
time = 0.01567363739013672 second
Dot product =2499266.1064
time = 2.8058009147644043 seconds
[0.41472435 0.98306583 0.21169921 0.57677065 0.63088672]
[0.13852931 0.84607535 0.73712684 0.60616276 0.0396947 ]


Now we find that Vectorization make code much faster because it use parallels technique   and also use both cpu and gpu

In [15]:
a = np.arange(6)
print(a)
a = np.arange(6).reshape(-1,2)
""".reshape(-1, 2) reshapes this 1D array into a 2D array with 2 columns and an appropriate number of rows.
 The -1 argument tells NumPy to automatically determine the number of rows based on the length of the array and the specified number of columns.
 """
print(a)



[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


# Slicing

In [32]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")
print("***********************************************************************")
"""   row                       column
      start:stop:step          index of column
                        or 
       index of row            start:stop:step

"""

print(a[:,2:6:1])
print("************************")
print(a[1,0::2]) #slice in second column to the end of array with step =2 



a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
***********************************************************************
[[ 2  3  4  5]
 [12 13 14 15]]
************************
[10 12 14 16 18]
