# Linear Regression with multiple Features
Problem Statement: Calculate housing price <br><br>
<img src =./Images/b12.png><img>

In [32]:
import math,copy
import numpy as np
import matplotlib as plt
np.set_printoptions(precision=2) # 2 digits after the decimal point to make numbers more readable

X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
print("Feature   Feature   Feature   Feature   Feature")
print(f"{X_train}\n shape {X_train.shape} (row,column) \n type {type(X_train)}")
y_train=np.array([460,232,178])

print(X_train.shape[0])
print(X_train.shape[-1])
print(X_train.shape)


Feature   Feature   Feature   Feature   Feature
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
 shape (3, 4) (row,column) 
 type <class 'numpy.ndarray'>
3
4
(3, 4)


<img src =./Images/b13.png></img>

One Weight per feature not per Iteration<br><br>
<img src =./Images/b14.png></img>

In [33]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618]) #one weight for each feature

<img src = ./Images/b15.png></img>

In [34]:
#compute_cost
def compute_cost(X,y,w,b):
    """
    X array 
    w vector
    b scalar
    """
    m=X.shape[0]
    cost=0
    for i in range(m):
        cost = cost + ( (np.dot(X[i],w)+b) - y[i] )**2

    cost=cost/(2*m)

    return cost
    

In [35]:
cost = compute_cost(X_train,y_train,w_init,b_init)
print(cost)

1.5578904428966628e-12


<img src = ./Images/b16.png/>

In [36]:
m=np.zeros(4)
print(m)

[0. 0. 0. 0.]


In [37]:
def compute_gradiant(X,y,w,b):
    """ 
        X array
        y scalar
        w vector 
        b scalr
        dj/dw = 1/m  sum of ((w*x+b)-y)*x sup(i) sub(j)     
        dj/db = 1/m  sum of ((w*x+b)-y)         

    """
    m,n = X.shape # rows and columns (iterations,features)
    d_dw = np.zeros(n)
    d_db=0
    for i in range(m):
        err = (np.dot(w,X[i])+b) -y[i]
        d_dw = d_dw + np.dot(err,X[i])
        
        d_db = d_db + err
    d_dw = d_dw / m                                
    d_db = d_db / m

    return d_dw,d_db
                        

In [38]:

tmp_d_dw,tmp_d_db = compute_gradiant(X_train,y_train,w_init,b_init)
print(f"{tmp_d_dw} \n  {tmp_d_db}")

[-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05] 
  -1.6739251501955248e-06


Gradiant Descent with multiple variables

In [39]:
def gradient_descent(X,y,w_in,b_in,cost_function,gradiant_function,learning_rate,num_iteration):
    """
    Repeat until convergence (repeat with many many iterations)
    w = w - learning rate * d/dw
    b = b - learning rate * d/db
    """
   
    J_history=[] # history of the cost
    w= copy.deepcopy(w_in)
    b =copy.deepcopy(b_in)
    for i in range(num_iteration):
        d_dw,d_db=gradiant_function(X,y,w,b)
        w = w - (learning_rate * d_dw)
        b = b - (learning_rate *d_db)
        if i < 100000:
            J_history.append(cost_function(X,y,w,b)) #store the history of the cost function

        if i% math.ceil(num_iteration/10)==0:
            print(f"Iteration {i:4d} : cost {J_history[-1]:8.2f}")
    
    return w,b,J_history

In [40]:
# initialize parameters
m,n = X_train.shape
initial_w = np.zeros(n)
initial_b = 0.
# some gradient descent settings
iterations = 1000
alpha = 5.0e-7
# run gradient descent 
w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b,compute_cost,compute_gradiant,alpha,iterations) 
            
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")

for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

Iteration    0 : cost  2529.46
Iteration  100 : cost   695.99
Iteration  200 : cost   694.92
Iteration  300 : cost   693.86
Iteration  400 : cost   692.81
Iteration  500 : cost   691.77
Iteration  600 : cost   690.73
Iteration  700 : cost   689.71
Iteration  800 : cost   688.70
Iteration  900 : cost   687.69
b,w found by gradient descent: -0.00,[ 0.2   0.   -0.01 -0.07] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
